const client = window.supabase.createClient(window.DELTA_SUPABASE.url, window.DELTA_SUPABASE.key);
const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];
const money = value => Number(value || 0).toLocaleString('zh-CN');
const labels = {pending:'待处理',approved:'已通过',rejected:'已拒绝',paused:'已暂停',confirmed:'已确认',active:'租用中',completed:'已完成',cancelled:'已取消',refunded:'已退款'};
let accounts=[], active='all', query='', orderDraft=null, session=null, profile=null, toastTimer;

function escapeHtml(value){return String(value ?? '').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function show(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2600)}
function statusChip(status){return `<span class="status-chip ${status}">${labels[status]||status}</span>`}
function setBusy(button,busy,text='处理中...'){if(!button)return;button.disabled=busy;if(busy){button.dataset.label=button.textContent;button.textContent=text}else if(button.dataset.label){button.textContent=button.dataset.label;delete button.dataset.label}}
function openPanel(id){['cartDrawer','authDrawer','sellerDrawer','adminDrawer'].forEach(name=>$('#'+name).classList.toggle('open',name===id));$('#overlay').classList.toggle('open',Boolean(id));document.body.style.overflow=id?'hidden':''}
$$('[data-close]').forEach(button=>button.onclick=()=>openPanel());$('#overlay').onclick=()=>openPanel();

function coinChoices(max){const values=[1000,3000,5000,10000].filter(value=>value<=max);if(!values.length)values.push(max);return values.map(value=>`<option value="${value}">${money(value)}万币</option>`).join('')}
function dayChoices(max){return [1,3,7,30].filter(value=>value<=max).map(value=>`<option value="${value}">${value}天</option>`).join('')}
async function loadAccounts(){
  $('#loadingState').classList.remove('hidden');
  const {data,error}=await client.from('listings').select('*').eq('status','approved').order('created_at',{ascending:false});
  $('#loadingState').classList.add('hidden');
  if(error){$('#backendStatus').textContent='连接异常';$('#productGrid').innerHTML=`<div class="error-box">账号同步失败，请稍后刷新</div>`;show(error.message);return}
  accounts=data||[];$('#backendStatus').textContent='已连接';$('#marketSummary').textContent=`当前 ${accounts.filter(item=>item.available).length} 个账号可租`;renderAccounts();
}
function renderAccounts(){
  const list=accounts.filter(item=>(active==='all'||item.category===active)&&(item.title+item.rank_name+item.feature+item.coins).toLowerCase().includes(query.toLowerCase()));
  $('#productGrid').innerHTML=list.map(item=>`<article class="product-card"><div class="account-visual"><span class="badge ${item.category==='starter'?'':'rare'}">${item.category==='wealth'?'高资产':item.category==='rank'?'高段位':'入门'}</span><span class="account-status ${item.available?'':'busy'}"><i></i>${item.available?'当前可租':'占用中'}</span><span class="account-id">${item.id.slice(0,4).toUpperCase()}</span><div class="rank-emblem"></div></div><div class="product-info"><span class="product-type">${escapeHtml(item.game_mode)} / ${escapeHtml(item.rank_name)}</span><h3>${escapeHtml(item.title)}</h3><div class="account-meta"><span class="coin-quota">可用 ${money(item.coins)}万哈夫币</span><span>${escapeHtml(item.feature)}</span></div><div class="rate-row"><div class="rate"><strong class="money">¥${money(item.unit_price)}</strong><small> / 1000万哈夫币</small><div class="quota-note">押金 ¥${money(item.deposit)} · 最长 ${item.max_days} 天</div></div><div class="rent-controls"><select class="duration coin-select">${coinChoices(item.coins)}</select><select class="duration day-select">${dayChoices(item.max_days)}</select><button class="rent-button" data-rent="${item.id}" ${item.available?'':'disabled'}>${item.available?'选择租用':'占用中'}</button></div></div></div></article>`).join('');
  $('#emptyState').style.display=list.length?'none':'block';
}
$$('[data-category]').forEach(button=>button.onclick=()=>{active=button.dataset.category;$$('[data-category]').forEach(item=>item.classList.toggle('active',item.dataset.category===active));renderAccounts();$('#market').scrollIntoView({behavior:'smooth'})});
$('#searchToggle').onclick=()=>{const panel=$('#searchPanel');panel.classList.toggle('open');if(panel.classList.contains('open'))setTimeout(()=>$('#searchInput').focus(),180)};
$('#searchInput').oninput=event=>{query=event.target.value;renderAccounts()};$('#clearSearch').onclick=()=>{$('#searchInput').value='';query='';renderAccounts()};
$('#productGrid').onclick=event=>{const button=event.target.closest('[data-rent]');if(!button)return;const item=accounts.find(account=>account.id===button.dataset.rent),controls=button.parentElement,coins=+controls.querySelector('.coin-select').value,days=+controls.querySelector('.day-select').value;orderDraft={...item,coinsSelected:coins,days,cost:Math.ceil(Number(item.unit_price)*coins/1000)};renderCart();openPanel('cartDrawer')};
function renderCart(){const item=orderDraft;$('#cartCount').textContent=item?1:0;$('#cartEmpty').style.display=item?'none':'block';$('#cartItems').innerHTML=item?`<div class="cart-item"><div><strong>${escapeHtml(item.title)}</strong><div class="order-meta"><span class="coin-line">${money(item.coinsSelected)}万哈夫币</span><span class="deadline">期限 ${item.days} 天</span><br>押金 ¥${money(item.deposit)}</div><small class="money">租金 ¥${money(item.cost)}</small></div><button class="remove" id="removeOrder">×</button></div>`:'';$('#cartTotal').textContent=money(item?.cost||0);$('#checkoutButton').disabled=!item;if(item)$('#removeOrder').onclick=()=>{orderDraft=null;renderCart()}}
$('#cartButton').onclick=()=>openPanel('cartDrawer');
$('#checkoutButton').onclick=async event=>{if(!orderDraft)return;if(!session){openPanel('authDrawer');show('请先登录后提交订单');return}setBusy(event.currentTarget,true,'提交中...');const {error}=await client.from('orders').insert({renter_id:session.user.id,listing_id:orderDraft.id,coins_amount:orderDraft.coinsSelected,duration_days:orderDraft.days,rental_fee:orderDraft.cost,deposit:orderDraft.deposit});setBusy(event.currentTarget,false);if(error){show(error.message);return}orderDraft=null;renderCart();openPanel();show('订单已提交，请等待管理员确认收款');loadMyOrders()};

$('#authButton').onclick=()=>openPanel('authDrawer');$$('[data-auth-tab]').forEach(button=>button.onclick=()=>{$$('[data-auth-tab]').forEach(item=>item.classList.toggle('active',item===button));$('#loginForm').classList.toggle('hidden',button.dataset.authTab!=='login');$('#registerForm').classList.toggle('hidden',button.dataset.authTab!=='register')});
$('#loginForm').onsubmit=async event=>{event.preventDefault();const button=event.currentTarget.querySelector('button'),form=new FormData(event.currentTarget);setBusy(button,true);const {error}=await client.auth.signInWithPassword({email:form.get('email'),password:form.get('password')});setBusy(button,false);if(error){show(error.message);return}show('登录成功')};
$('#registerForm').onsubmit=async event=>{event.preventDefault();const button=event.currentTarget.querySelector('button'),form=new FormData(event.currentTarget);setBusy(button,true);const {data,error}=await client.auth.signUp({email:form.get('email'),password:form.get('password'),options:{data:{display_name:form.get('displayName')}}});setBusy(button,false);if(error){show(error.message);return}event.currentTarget.reset();show(data.session?'注册并登录成功':'注册成功，请前往邮箱确认')};
$('#logoutButton').onclick=async()=>{await client.auth.signOut();openPanel();show('已退出登录')};
async function applySession(nextSession){session=nextSession;profile=null;$('#authGuest').classList.toggle('hidden',Boolean(session));$('#authUser').classList.toggle('hidden',!session);if(!session){$('#authLabel').textContent='登录 / 注册';$('#adminButton').classList.add('hidden');return}const {data}=await client.from('profiles').select('*').eq('id',session.user.id).single();profile=data;$('#authLabel').textContent=data?.display_name||session.user.email.split('@')[0];$('#profileName').textContent=data?.display_name||'用户';$('#profileEmail').textContent=session.user.email;$('#profileRole').textContent=data?.role==='admin'?'平台管理员':'普通用户';$('#bootstrapCard').classList.toggle('hidden',data?.role==='admin');$('#adminButton').classList.toggle('hidden',data?.role!=='admin');loadMyOrders()}
$('#claimAdmin').onclick=async event=>{const code=$('#bootstrapCode').value.trim();if(!code){show('请输入管理员初始化码');return}setBusy(event.currentTarget,true);const {error}=await client.rpc('claim_initial_admin',{secret:code});setBusy(event.currentTarget,false);if(error){show(error.message);return}$('#bootstrapCode').value='';await applySession(session);show('管理员权限已启用')};
async function loadMyOrders(){if(!session)return;const {data,error}=await client.from('orders').select('*,listings(title)').eq('renter_id',session.user.id).order('created_at',{ascending:false});if(error){$('#myOrders').innerHTML=`<div class="error-box">${escapeHtml(error.message)}</div>`;return}$('#myOrders').innerHTML=data?.length?data.map(item=>`<article class="record-card"><strong>${escapeHtml(item.listings?.title||'账号订单')} ${statusChip(item.status)}</strong><p>${money(item.coins_amount)}万哈夫币 · ${item.duration_days}天 · 租金¥${money(item.rental_fee)}<br>支付：${labels[item.payment_status]||item.payment_status} · ${new Date(item.created_at).toLocaleString('zh-CN')}</p></article>`).join(''):'<div class="empty-small">暂无订单</div>'}
$('#refreshOrders').onclick=loadMyOrders;

$('#sellerButton').onclick=()=>{if(!session){openPanel('authDrawer');show('请先登录后上架账号');return}openPanel('sellerDrawer');loadMyListings()};$$('[data-seller-tab]').forEach(button=>button.onclick=()=>{$$('[data-seller-tab]').forEach(item=>item.classList.toggle('active',item===button));$('#listingForm').classList.toggle('hidden',button.dataset.sellerTab!=='form');$('#myListings').classList.toggle('active',button.dataset.sellerTab==='mine');if(button.dataset.sellerTab==='mine')loadMyListings()});
$('#proofInput').onchange=event=>{$('#proofText').textContent=event.target.files[0]?.name||'点击选择哈夫币余额或段位截图'};
$('#listingForm').onsubmit=async event=>{event.preventDefault();if(!session)return;const button=event.currentTarget.querySelector('.submit-listing'),form=new FormData(event.currentTarget),file=$('#proofInput').files[0];if(!file||file.size>5242880){show('请选择不超过5MB的图片');return}setBusy(button,true,'上传并提交...');const safeName=file.name.replace(/[^a-zA-Z0-9._-]/g,'_'),path=`${session.user.id}/${Date.now()}-${safeName}`;const upload=await client.storage.from('listing-proofs').upload(path,file,{upsert:false});if(upload.error){setBusy(button,false);show(upload.error.message);return}const payload={owner_id:session.user.id,title:form.get('title'),category:form.get('category'),game_mode:form.get('game_mode'),rank_name:form.get('rank_name'),coins:+form.get('coins'),feature:form.get('feature'),unit_price:+form.get('unit_price'),max_days:+form.get('max_days'),deposit:+form.get('deposit'),proof_path:path,status:'pending',available:false};const {error}=await client.from('listings').insert(payload);setBusy(button,false);if(error){await client.storage.from('listing-proofs').remove([path]);show(error.message);return}event.currentTarget.reset();$('#proofText').textContent='点击选择哈夫币余额或段位截图';show('已提交审核');$$('[data-seller-tab="mine"]')[0].click()};
async function loadMyListings(){if(!session)return;const {data,error}=await client.from('listings').select('*').eq('owner_id',session.user.id).order('created_at',{ascending:false});if(error){$('#myListings').innerHTML=`<div class="error-box">${escapeHtml(error.message)}</div>`;return}$('#myCount').textContent=data?.length||0;$('#myListings').innerHTML=data?.length?data.map(item=>`<article class="my-listing"><div class="my-listing-head"><strong>${escapeHtml(item.title)}</strong>${statusChip(item.status)}</div><p>${escapeHtml(item.game_mode)} / ${escapeHtml(item.rank_name)} · ${money(item.coins)}万哈夫币<br>${escapeHtml(item.review_note||'暂无审核备注')}</p><div class="my-listing-foot"><span>¥${money(item.unit_price)}/1000万币 · 最长${item.max_days}天</span>${['pending','rejected'].includes(item.status)?`<button class="delete-listing" data-delete-listing="${item.id}" data-proof="${escapeHtml(item.proof_path)}">撤回</button>`:''}</div></article>`).join(''):'<div class="my-empty"><span>△</span><strong>暂无上架记录</strong><p>提交资料后可在这里查看审核进度</p></div>'}
$('#myListings').onclick=async event=>{const button=event.target.closest('[data-delete-listing]');if(!button)return;button.disabled=true;const {error}=await client.from('listings').delete().eq('id',button.dataset.deleteListing);if(error){show(error.message);button.disabled=false;return}await client.storage.from('listing-proofs').remove([button.dataset.proof]);show('已撤回上架申请');loadMyListings()};

$('#adminButton').onclick=()=>{openPanel('adminDrawer');loadAdminListings();loadAdminOrders();loadAdminStats()};$$('[data-admin-tab]').forEach(button=>button.onclick=()=>{$$('[data-admin-tab]').forEach(item=>item.classList.toggle('active',item===button));$$('.admin-pane').forEach(pane=>pane.classList.remove('active'));$('#admin'+button.dataset.adminTab[0].toUpperCase()+button.dataset.adminTab.slice(1)).classList.add('active')});
async function audit(action,type,id,details={}){if(!profile)return;await client.from('audit_logs').insert({admin_id:profile.id,action,entity_type:type,entity_id:id,details})}
async function loadAdminListings(){const {data,error}=await client.from('listings').select('*').order('created_at',{ascending:false});if(error){$('#adminListings').innerHTML=`<div class="error-box">${escapeHtml(error.message)}</div>`;return}$('#adminListings').innerHTML=data?.length?data.map(item=>`<article class="admin-card"><div class="admin-card-head"><h3>${escapeHtml(item.title)}</h3>${statusChip(item.status)}</div><p>${escapeHtml(item.game_mode)} / ${escapeHtml(item.rank_name)} · ${money(item.coins)}万哈夫币 · ¥${money(item.unit_price)}/1000万币<br>${escapeHtml(item.feature)} · 押金¥${money(item.deposit)} · 最长${item.max_days}天</p><div class="admin-actions"><button class="proof" data-proof-view="${escapeHtml(item.proof_path)}">查看验号图</button>${item.status!=='approved'?`<button class="approve" data-listing-action="approve" data-id="${item.id}">通过</button>`:''}${item.status!=='rejected'?`<button class="reject" data-listing-action="reject" data-id="${item.id}">拒绝</button>`:''}${item.status==='approved'?`<button data-listing-action="pause" data-id="${item.id}">${item.available?'暂停出租':'恢复出租'}</button>`:''}</div></article>`).join(''):'<div class="empty-small">暂无账号</div>'}
$('#adminListings').onclick=async event=>{const proof=event.target.closest('[data-proof-view]');if(proof){if(proof.dataset.proofView.startsWith('platform/')){show('平台初始账号没有上传验号图');return}const {data,error}=await client.storage.from('listing-proofs').createSignedUrl(proof.dataset.proofView,60);if(error){show(error.message);return}window.open(data.signedUrl,'_blank');return}const button=event.target.closest('[data-listing-action]');if(!button)return;setBusy(button,true);let update={},action=button.dataset.listingAction;if(action==='approve')update={status:'approved',available:true,review_note:'审核通过'};if(action==='reject')update={status:'rejected',available:false,review_note:'资料未通过，请修改后重新提交'};if(action==='pause'){const item=accounts.find(x=>x.id===button.dataset.id);update={status:'approved',available:!(item?.available??true)}}const {error}=await client.from('listings').update(update).eq('id',button.dataset.id);setBusy(button,false);if(error){show(error.message);return}await audit(`listing_${action}`,'listing',button.dataset.id,update);show('账号状态已更新');await loadAccounts();loadAdminListings();loadAdminStats()};
async function loadAdminOrders(){const {data,error}=await client.from('orders').select('*,listings(title)').order('created_at',{ascending:false});if(error){$('#adminOrders').innerHTML=`<div class="error-box">${escapeHtml(error.message)}</div>`;return}$('#adminOrders').innerHTML=data?.length?data.map(item=>`<article class="admin-card"><div class="admin-card-head"><h3>${escapeHtml(item.listings?.title||'账号订单')}</h3>${statusChip(item.status)}</div><p>${money(item.coins_amount)}万哈夫币 · ${item.duration_days}天 · 租金¥${money(item.rental_fee)} · 押金¥${money(item.deposit)}<br>支付状态：${labels[item.payment_status]||item.payment_status} · ${new Date(item.created_at).toLocaleString('zh-CN')}</p><div class="admin-actions">${item.payment_status==='pending'?`<button class="approve" data-order-action="confirm" data-id="${item.id}">确认收款</button>`:''}${item.status==='confirmed'?`<button class="approve" data-order-action="activate" data-id="${item.id}" data-days="${item.duration_days}">开始租用</button>`:''}${item.status==='active'?`<button class="approve" data-order-action="complete" data-id="${item.id}">完成订单</button>`:''}${!['completed','cancelled'].includes(item.status)?`<button class="reject" data-order-action="cancel" data-id="${item.id}">取消/退款</button>`:''}</div></article>`).join(''):'<div class="empty-small">暂无订单</div>'}
$('#adminOrders').onclick=async event=>{const button=event.target.closest('[data-order-action]');if(!button)return;setBusy(button,true);const action=button.dataset.orderAction,now=new Date(),update={};if(action==='confirm'){update.payment_status='confirmed';update.status='confirmed'}if(action==='activate'){update.status='active';update.starts_at=now.toISOString();update.expires_at=new Date(now.getTime()+(+button.dataset.days)*86400000).toISOString()}if(action==='complete')update.status='completed';if(action==='cancel'){update.status='cancelled';update.payment_status='refunded'}const {error}=await client.from('orders').update(update).eq('id',button.dataset.id);setBusy(button,false);if(error){show(error.message);return}await audit(`order_${action}`,'order',button.dataset.id,update);show('订单状态已更新');loadAdminOrders();loadAdminStats()};
async function loadAdminStats(){const [listings,orders,users,pending]=await Promise.all([client.from('listings').select('*',{count:'exact',head:true}),client.from('orders').select('*',{count:'exact',head:true}),client.from('profiles').select('*',{count:'exact',head:true}),client.from('listings').select('*',{count:'exact',head:true}).eq('status','pending')]);$('#adminStats').innerHTML=`<div class="stat-grid"><div class="stat-box"><span>全部账号</span><strong>${listings.count||0}</strong></div><div class="stat-box"><span>全部订单</span><strong>${orders.count||0}</strong></div><div class="stat-box"><span>注册用户</span><strong>${users.count||0}</strong></div><div class="stat-box"><span>待审核</span><strong>${pending.count||0}</strong></div></div>`}

client.auth.onAuthStateChange((_event,nextSession)=>setTimeout(()=>applySession(nextSession),0));
(async()=>{const {data}=await client.auth.getSession();await applySession(data.session);renderCart();await loadAccounts()})();
