const accounts=[
 {id:'D-071',name:'亿级哈夫币 · 满改枪库',category:'wealth',rank:'烽火地带 / 钻石',coins:12800,feature:'典藏外观 18件',unitPrice:120,deposit:200,maxDays:7,available:true,tag:'高资产'},
 {id:'D-114',name:'高段位 · 战神账号',category:'rank',rank:'全面战场 / 战神',coins:6800,feature:'全干员解锁',unitPrice:150,deposit:300,maxDays:3,available:true,tag:'高段位'},
 {id:'D-208',name:'新手畅玩 · 免押套餐',category:'starter',rank:'烽火地带 / 青铜',coins:1500,feature:'基础枪械齐全',unitPrice:80,deposit:0,maxDays:7,available:true,tag:'免押'},
 {id:'D-327',name:'收藏家 · 典藏皮肤库',category:'wealth',rank:'双模式 / 铂金',coins:7600,feature:'典藏外观 41件',unitPrice:180,deposit:300,maxDays:7,available:true,tag:'典藏'},
 {id:'D-416',name:'冲分专用 · 全面战场',category:'rank',rank:'全面战场 / 王牌',coins:5000,feature:'赛季胜率 68%',unitPrice:100,deposit:200,maxDays:3,available:false,tag:'热门'},
 {id:'D-552',name:'轻装体验 · 标准账号',category:'starter',rank:'双模式 / 白银',coins:3000,feature:'常用干员解锁',unitPrice:90,deposit:100,maxDays:7,available:true,tag:'入门'}
];
let active='all',query='',orders=[],myListings=loadListings();const $=s=>document.querySelector(s),grid=$('#productGrid'),money=n=>n.toLocaleString('zh-CN');
function loadListings(){try{return JSON.parse(localStorage.getItem('delta-my-listings')||'[]')}catch{return[]}}function saveListings(){localStorage.setItem('delta-my-listings',JSON.stringify(myListings))}
function coinChoices(max){const standard=[1000,3000,5000,10000].filter(n=>n<=max);if(!standard.length)standard.push(max);return standard.map(n=>`<option value="${n}">${n}万币</option>`).join('')}function dayChoices(max){return[1,3,7,30].filter(n=>n<=max).map(n=>`<option value="${n}">${n}天</option>`).join('')}
function render(){const list=accounts.filter(a=>(active==='all'||a.category===active)&&(a.name+a.id+a.rank+a.feature+a.coins+'万哈夫币').toLowerCase().includes(query.toLowerCase()));grid.innerHTML=list.map(a=>`<article class="product-card"><div class="account-visual"><span class="badge ${a.category==='starter'?'':'rare'}">${a.tag}</span><span class="account-status ${a.available?'':'busy'}"><i></i>${a.available?'当前可租':'租用中'}</span><span class="account-id">${a.id}</span><div class="rank-emblem"></div></div><div class="product-info"><span class="product-type">账号编号 ${a.id}</span><h3>${a.name}</h3><div class="account-meta"><span>${a.rank}</span><span class="coin-quota">可用 ${money(a.coins)}万哈夫币</span><span>${a.feature}</span></div><div class="rate-row"><div class="rate"><strong class="money">¥${a.unitPrice}</strong><small> / 1000万哈夫币</small><div class="quota-note">押金 ¥${a.deposit} · 最长 ${a.maxDays} 天</div></div><div class="rent-controls"><select class="duration coin-select" aria-label="哈夫币额度">${coinChoices(a.coins)}</select><select class="duration day-select" aria-label="租号期限">${dayChoices(a.maxDays)}</select><button class="rent-button" data-rent="${a.id}" ${a.available?'':'disabled'}>${a.available?'选择租用':'占用中'}</button></div></div></div></article>`).join('');$('#emptyState').style.display=list.length?'none':'block'}
function chooseCategory(c){active=c;document.querySelectorAll('[data-category]').forEach(b=>b.classList.toggle('active',b.dataset.category===c));render();$('#market').scrollIntoView({behavior:'smooth'})}document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>chooseCategory(b.dataset.category));
grid.onclick=e=>{const b=e.target.closest('[data-rent]');if(!b)return;const a=accounts.find(x=>x.id===b.dataset.rent),controls=b.parentElement,coins=+controls.querySelector('.coin-select').value,days=+controls.querySelector('.day-select').value,cost=Math.ceil(a.unitPrice*coins/1000);orders=[{...a,coinsSelected:coins,days,cost,line:Date.now()}];renderOrders();openPanel('cart');show(`已选择 ${coins}万哈夫币，租期 ${days} 天`)};
function renderOrders(){const box=$('#cartItems');box.innerHTML=orders.map(o=>`<div class="cart-item"><div><strong>${o.name}</strong><div class="order-meta"><span class="coin-line">${money(o.coinsSelected)}万哈夫币</span><span class="deadline">期限 ${o.days} 天</span><br>账号 ${o.id} · 押金 ¥${o.deposit}</div><small class="money">租金 ¥${money(o.cost)}</small></div><button class="remove" data-remove="${o.line}">×</button></div>`).join('');$('#cartCount').textContent=orders.length;$('#cartTotal').textContent=money(orders.reduce((s,o)=>s+o.cost,0));$('#cartEmpty').style.display=orders.length?'none':'block';$('#checkoutButton').disabled=!orders.length}
$('#cartItems').onclick=e=>{const b=e.target.closest('[data-remove]');if(b){orders=orders.filter(o=>o.line!==+b.dataset.remove);renderOrders()}};
const cart=$('#cartDrawer'),seller=$('#sellerDrawer'),overlay=$('#overlay');function openPanel(which){cart.classList.toggle('open',which==='cart');seller.classList.toggle('open',which==='seller');overlay.classList.toggle('open',!!which);document.body.style.overflow=which?'hidden':''}$('#cartButton').onclick=()=>openPanel('cart');$('#closeCart').onclick=()=>openPanel();$('#sellerButton').onclick=()=>openPanel('seller');$('#closeSeller').onclick=()=>openPanel();overlay.onclick=()=>openPanel();
const panel=$('#searchPanel'),input=$('#searchInput');$('#searchToggle').onclick=()=>{panel.classList.toggle('open');if(panel.classList.contains('open'))setTimeout(()=>input.focus(),180)};input.oninput=()=>{query=input.value;render()};$('#clearSearch').onclick=()=>{query='';input.value='';render()};$('#checkoutButton').onclick=()=>{openPanel();orders=[];renderOrders();show('订单已提交，请登录后完成实名认证与支付')};
function setSellerTab(tab){document.querySelectorAll('.seller-tab').forEach(b=>b.classList.toggle('active',b.dataset.sellerTab===tab));$('#listingForm').classList.toggle('hidden',tab!=='form');$('#myListings').classList.toggle('active',tab==='mine')}document.querySelectorAll('.seller-tab').forEach(b=>b.onclick=()=>setSellerTab(b.dataset.sellerTab));$('#proofInput').onchange=e=>{$('#proofText').textContent=e.target.files[0]?.name||'点击选择哈夫币余额或段位截图'};
function renderMyListings(){$('#myCount').textContent=myListings.length;$('#myListings').innerHTML=myListings.length?myListings.map(x=>{const coins=x.coins||x.assets||'待补充',price=x.unitPrice||x.rate||0,days=x.maxDays||7;return`<article class="my-listing"><div class="my-listing-head"><strong>${escapeHtml(x.name)}</strong><span class="reviewing">● 审核中</span></div><p>${escapeHtml(x.mode)} / ${escapeHtml(x.rank)} · ${escapeHtml(coins)}万哈夫币<br>${escapeHtml(x.feature)} · 验号图 ${escapeHtml(x.proof)}</p><div class="my-listing-foot"><span>¥${price}/1000万币 · 最长${days}天 · 押金¥${x.deposit}</span><button class="delete-listing" data-delete="${x.id}">撤回上架</button></div></article>`}).join(''):`<div class="my-empty"><span>△</span><strong>暂无上架记录</strong><p>提交账号资料后可在这里查看审核进度</p></div>`}
$('#listingForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),file=$('#proofInput').files[0];if(!file)return;myListings.unshift({id:`U-${Date.now()}`,name:f.get('name'),category:f.get('category'),mode:f.get('mode'),rank:f.get('rank'),coins:+f.get('coins'),feature:f.get('feature'),unitPrice:+f.get('unitPrice'),maxDays:+f.get('maxDays'),deposit:+f.get('deposit'),proof:file.name,created:new Date().toISOString()});saveListings();renderMyListings();e.currentTarget.reset();$('#proofText').textContent='点击选择哈夫币余额或段位截图';setSellerTab('mine');show('账号资料已提交，平台将在核验哈夫币后联系你')};
$('#myListings').onclick=e=>{const b=e.target.closest('[data-delete]');if(!b)return;myListings=myListings.filter(x=>x.id!==b.dataset.delete);saveListings();renderMyListings();show('已撤回该上架申请')};function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
let timer;function show(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>e.classList.remove('show'),2400)}render();renderOrders();renderMyListings();
