(function(){
  const css=document.createElement('link');css.rel='stylesheet';css.href='payments.css';document.head.appendChild(css);
  const safe=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const amount=value=>Number(value||0).toLocaleString('zh-CN');
  let paymentSettings={support_contact:'微信 G644373420',payment_instructions:'请核对订单金额后使用官方微信收款码付款，并上传付款凭证。管理员核验后开始租用。',payment_qr_url:''};

  async function fetchPaymentSettings(){const {data}=await client.rpc('get_public_settings');(data||[]).forEach(item=>paymentSettings[item.key]=item.value);return paymentSettings}

  const settingBox=document.querySelector('#adminSettings .operations-box');
  const qrBlock=document.createElement('div');qrBlock.innerHTML='<label>微信收款码图片<input id="paymentQrFile" type="file" accept="image/jpeg,image/png,image/webp"></label><img id="paymentQrPreview" class="qr-admin-preview hidden" alt="当前微信收款码"><button id="uploadPaymentQr" class="qr-upload-button" type="button">上传并启用收款码</button>';
  settingBox.appendChild(qrBlock);
  async function refreshQrAdmin(){await fetchPaymentSettings();const image=document.querySelector('#paymentQrPreview');image.src=paymentSettings.payment_qr_url||'';image.classList.toggle('hidden',!paymentSettings.payment_qr_url)}
  document.querySelector('#paymentQrFile').onchange=event=>{const file=event.target.files[0];if(file)document.querySelector('#paymentQrPreview').src=URL.createObjectURL(file)};
  document.querySelector('#uploadPaymentQr').onclick=async event=>{const file=document.querySelector('#paymentQrFile').files[0];if(!file||file.size>5242880){show('请选择不超过 5MB 的收款码图片');return}setBusy(event.currentTarget,true,'上传中...');const extension=(file.name.split('.').pop()||'png').replace(/[^a-z0-9]/gi,'').toLowerCase(),path=`payment/wechat-${Date.now()}.${extension}`;const upload=await client.storage.from('platform-assets').upload(path,file,{upsert:false,contentType:file.type});if(upload.error){setBusy(event.currentTarget,false);show(friendlyError(upload.error));return}const {data:publicData}=client.storage.from('platform-assets').getPublicUrl(path);const {error}=await client.rpc('update_payment_qr_url',{qr_url:publicData.publicUrl});setBusy(event.currentTarget,false);if(error){show(friendlyError(error));return}paymentSettings.payment_qr_url=publicData.publicUrl;document.querySelector('#paymentQrFile').value='';await refreshQrAdmin();show('微信收款码已启用')};
  document.querySelector('#adminButton').addEventListener('click',refreshQrAdmin);

  loadMyOrders=async function(){
    if(!session)return;await fetchPaymentSettings();
    const {data,error}=await client.from('orders').select('*,listings(title)').eq('renter_id',session.user.id).order('created_at',{ascending:false});
    if(error){document.querySelector('#myOrders').innerHTML=`<div class="error-box">${safe(friendlyError(error))}</div>`;return}
    document.querySelector('#myOrders').innerHTML=data?.length?data.map(item=>{const pending=item.status==='pending'&&item.payment_status==='pending',total=Number(item.rental_fee)+Number(item.deposit);const expiry=pending&&item.payment_expires_at?`<br><span class="expiry-note">请在 ${new Date(item.payment_expires_at).toLocaleString('zh-CN')} 前提交付款凭证，超时自动释放</span>`:'';const active=item.status==='active'&&item.expires_at?`<br>到期：${new Date(item.expires_at).toLocaleString('zh-CN')}`:'';let payment='';if(pending){payment=`<div class="payment-panel"><h4>微信付款</h4><p>官方联系：${safe(paymentSettings.support_contact)}</p><p>${safe(paymentSettings.payment_instructions)}</p>${paymentSettings.payment_qr_url?`<img class="payment-qr" src="${safe(paymentSettings.payment_qr_url)}" alt="微信收款码"><p class="payment-total">应付合计 ¥${amount(total)}</p>`:'<p class="payment-warning">收款码尚未上传，请先联系官方微信获取。</p>'}${item.payment_proof_path?'<span class="proof-submitted">付款凭证已提交，等待管理员核验</span>':`<label class="proof-upload">上传付款凭证<input type="file" accept="image/jpeg,image/png,image/webp" data-proof-file="${item.id}"><button type="button" data-submit-proof="${item.id}">提交付款凭证</button></label>`}<div class="order-actions-inline"><small>尚未确认收款</small><button class="cancel-own-order" data-cancel-own="${item.id}">取消订单</button></div></div>`}return `<article class="record-card"><strong>${safe(item.listings?.title||'账号订单')} ${statusChip(item.status)}</strong><p>${amount(item.coins_amount)}万哈夫币 · ${item.duration_days}天 · 租金¥${amount(item.rental_fee)} · 押金¥${amount(item.deposit)}<br>支付：${labels[item.payment_status]||item.payment_status} · ${new Date(item.created_at).toLocaleString('zh-CN')}${expiry}${active}</p>${payment}</article>`}).join(''):'<div class="empty-small">暂无订单</div>';
  };
  document.querySelector('#myOrders').onclick=async event=>{const cancel=event.target.closest('[data-cancel-own]');if(cancel){setBusy(cancel,true,'取消中...');const {error}=await client.rpc('cancel_my_pending_order',{target_order:cancel.dataset.cancelOwn});setBusy(cancel,false);if(error){show(friendlyError(error));return}show('订单已取消，账号已经释放');await Promise.all([loadMyOrders(),loadAccounts()]);return}const button=event.target.closest('[data-submit-proof]');if(!button)return;const input=document.querySelector(`[data-proof-file="${button.dataset.submitProof}"]`),file=input.files[0];if(!file||file.size>5242880){show('请选择不超过 5MB 的付款凭证');return}setBusy(button,true,'上传中...');const extension=(file.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'').toLowerCase(),path=`${session.user.id}/${button.dataset.submitProof}-${Date.now()}.${extension}`;const upload=await client.storage.from('payment-proofs').upload(path,file,{upsert:false,contentType:file.type});if(upload.error){setBusy(button,false);show(friendlyError(upload.error));return}const {error}=await client.rpc('submit_payment_proof',{target_order:button.dataset.submitProof,proof_path:path});setBusy(button,false);if(error){await client.storage.from('payment-proofs').remove([path]);show(friendlyError(error));return}show('付款凭证已提交');loadMyOrders()};
  document.querySelector('#refreshOrders').onclick=loadMyOrders;

  loadAdminOrders=async function(){const {data,error}=await client.from('orders').select('*,listings(title)').order('created_at',{ascending:false});if(error){document.querySelector('#adminOrders').innerHTML=`<div class="error-box">${safe(friendlyError(error))}</div>`;return}document.querySelector('#adminOrders').innerHTML=data?.length?data.map(item=>`<article class="admin-card"><div class="admin-card-head"><h3>${safe(item.listings?.title||'账号订单')}</h3>${statusChip(item.status)}</div><p>${amount(item.coins_amount)}万哈夫币 · ${item.duration_days}天 · 租金¥${amount(item.rental_fee)} · 押金¥${amount(item.deposit)}<br>支付状态：${labels[item.payment_status]||item.payment_status} · ${new Date(item.created_at).toLocaleString('zh-CN')}</p><p class="contact-line">客户联系：${safe(item.contact||'旧订单未填写')}</p><div class="admin-actions">${item.contact?`<button class="copy-contact" data-copy-contact="${safe(item.contact)}">复制联系方式</button>`:''}${item.payment_proof_path?`<button class="payment-proof-button" data-payment-proof="${safe(item.payment_proof_path)}">查看付款凭证</button>`:''}${item.payment_status==='pending'?`<button class="approve" data-order-action="confirm" data-id="${item.id}">确认收款</button>`:''}${item.status==='confirmed'?`<button class="approve" data-order-action="activate" data-id="${item.id}" data-days="${item.duration_days}">开始租用</button>`:''}${item.status==='active'?`<button class="approve" data-order-action="complete" data-id="${item.id}">完成订单</button>`:''}${!['completed','cancelled'].includes(item.status)?`<button class="reject" data-order-action="cancel" data-id="${item.id}">取消/退款</button>`:''}</div></article>`).join(''):'<div class="empty-small">暂无订单</div>'};
  document.querySelector('#adminOrders').onclick=async event=>{const proof=event.target.closest('[data-payment-proof]');if(proof){const {data,error}=await client.storage.from('payment-proofs').createSignedUrl(proof.dataset.paymentProof,120);if(error){show(friendlyError(error));return}window.open(data.signedUrl,'_blank','noopener');return}const copy=event.target.closest('[data-copy-contact]');if(copy){try{await navigator.clipboard.writeText(copy.dataset.copyContact);show('联系方式已复制')}catch{show(`联系方式：${copy.dataset.copyContact}`)}return}const button=event.target.closest('[data-order-action]');if(!button)return;setBusy(button,true);const action=button.dataset.orderAction,now=new Date(),update={};if(action==='confirm'){update.payment_status='confirmed';update.status='confirmed'}if(action==='activate'){update.status='active';update.starts_at=now.toISOString();update.expires_at=new Date(now.getTime()+(+button.dataset.days)*86400000).toISOString()}if(action==='complete')update.status='completed';if(action==='cancel'){update.status='cancelled';update.payment_status='cancelled'}const {error}=await client.from('orders').update(update).eq('id',button.dataset.id);setBusy(button,false);if(error){show(friendlyError(error));return}await audit(`order_${action}`,'order',button.dataset.id,update);show('订单状态已更新');await Promise.all([loadAdminOrders(),loadAdminStats(),loadAdminListings(),loadAccounts()])};

  fetchPaymentSettings();if(session)loadMyOrders();
})();
